//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSD.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        internal static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active project.
        /// </summary>
        internal static string ActiveProject {
            get {
                return ResourceManager.GetString("ActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another.
        /// </summary>
        internal static string AddAnother {
            get {
                return ResourceManager.GetString("AddAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new entry.
        /// </summary>
        internal static string AddNewEntry {
            get {
                return ResourceManager.GetString("AddNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        internal static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database path.
        /// </summary>
        internal static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry.
        /// </summary>
        internal static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the project &apos;{0}&apos;?.
        /// </summary>
        internal static string DoYouReallyWantToDeleteProjectXXX {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteProjectXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the tag &apos;{0}&apos;?.
        /// </summary>
        internal static string DoYouReallyWantToDeleteTagXXX {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteTagXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this entry?.
        /// </summary>
        internal static string DoYouReallyWantToDeleteThisEntry {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteThisEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry.
        /// </summary>
        internal static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new database path.
        /// </summary>
        internal static string EnterNewDatabasePath {
            get {
                return ResourceManager.GetString("EnterNewDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the entry (Markdown is supported).
        /// </summary>
        internal static string EntryDetails {
            get {
                return ResourceManager.GetString("EntryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry needs summary.
        /// </summary>
        internal static string EntryNeedsSummary {
            get {
                return ResourceManager.GetString("EntryNeedsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the entry.
        /// </summary>
        internal static string EntrySummary {
            get {
                return ResourceManager.GetString("EntrySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand entries.
        /// </summary>
        internal static string ExpandEntries {
            get {
                return ResourceManager.GetString("ExpandEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage projects.
        /// </summary>
        internal static string ManageProjects {
            get {
                return ResourceManager.GetString("ManageProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage tags.
        /// </summary>
        internal static string ManageTags {
            get {
                return ResourceManager.GetString("ManageTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Markdown supported).
        /// </summary>
        internal static string MarkdownSupported {
            get {
                return ResourceManager.GetString("MarkdownSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move database.
        /// </summary>
        internal static string MoveDatabase {
            get {
                return ResourceManager.GetString("MoveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After moving the database, the application will be restarted..
        /// </summary>
        internal static string MoveDatabaseMessage {
            get {
                return ResourceManager.GetString("MoveDatabaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving database.
        /// </summary>
        internal static string MovingDatabase {
            get {
                return ResourceManager.GetString("MovingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must be valid.
        /// </summary>
        internal static string MustEnterValidPath {
            get {
                return ResourceManager.GetString("MustEnterValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database path.
        /// </summary>
        internal static string NewDatabasePath {
            get {
                return ResourceManager.GetString("NewDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entry.
        /// </summary>
        internal static string NewEntry {
            get {
                return ResourceManager.GetString("NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries defined.
        /// </summary>
        internal static string NoEntriesDefined {
            get {
                return ResourceManager.GetString("NoEntriesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects defined.
        /// </summary>
        internal static string NoProjectsDefined {
            get {
                return ResourceManager.GetString("NoProjectsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags defined for this project.
        /// </summary>
        internal static string NoTagsDefinedForProject {
            get {
                return ResourceManager.GetString("NoTagsDefinedForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open: {0}.
        /// </summary>
        internal static string OpenEntries {
            get {
                return ResourceManager.GetString("OpenEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project must have a name.
        /// </summary>
        internal static string ProjectMustHaveName {
            get {
                return ResourceManager.GetString("ProjectMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report error.
        /// </summary>
        internal static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        internal static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all completed entries.
        /// </summary>
        internal static string SearchAllCompletedEntries {
            get {
                return ResourceManager.GetString("SearchAllCompletedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all containing &apos;test 123&apos; in details.
        /// </summary>
        internal static string SearchAllEntriesContaining {
            get {
                return ResourceManager.GetString("SearchAllEntriesContaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all entries tagged &apos;abc&apos;.
        /// </summary>
        internal static string SearchAllEntriesTagged {
            get {
                return ResourceManager.GetString("SearchAllEntriesTagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all open entries.
        /// </summary>
        internal static string SearchAllOpenEntries {
            get {
                return ResourceManager.GetString("SearchAllOpenEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search did not return any matches.
        /// </summary>
        internal static string SearchDidNotReturnAnyMatches {
            get {
                return ResourceManager.GetString("SearchDidNotReturnAnyMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is done using AND.
        /// </summary>
        internal static string SearchIsDoneUsingAND {
            get {
                return ResourceManager.GetString("SearchIsDoneUsingAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search matches: {0}.
        /// </summary>
        internal static string SearchMatches {
            get {
                return ResourceManager.GetString("SearchMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        internal static string StartMinimized {
            get {
                return ResourceManager.GetString("StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with windows.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag must have a name.
        /// </summary>
        internal static string TagMustHaveName {
            get {
                return ResourceManager.GetString("TagMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already used.
        /// </summary>
        internal static string ThisNameIsAlreadyUsed {
            get {
                return ResourceManager.GetString("ThisNameIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        internal static string TotalEntries {
            get {
                return ResourceManager.GetString("TotalEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
